# Generated by Django 5.2.1 on 2025-06-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tarefaagenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaagenda',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefaagenda',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.materia'),
        ),
    ]
