# Generated by Django 5.2.1 on 2025-06-16 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_tarefaagenda_data_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='comentarios/arquivos/')),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='app.comentario')),
            ],
        ),
    ]
