# Generated by Django 5.2.1 on 2025-09-14 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_arquivocomentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField()),
                ('template_key', models.CharField(blank=True, choices=[('conceito', 'Conceito a Fundo'), ('projeto', 'Projeto Real'), ('revisao', 'Revisão'), ('skill', 'Aprendizado por Skill'), ('profissional', 'Desenvolvimento Profissional'), ('escrita', 'Escrita Técnica'), ('checklist', 'Checklist Técnico'), ('simulacao', 'Simulação de Projeto')], max_length=30, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, db_column='criado_em')),
                ('date_updated', models.DateTimeField(auto_now=True, db_column='atualizado_em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_prompt',
                'ordering': ['-date_updated'],
            },
        ),
    ]
